services:
    marttiphpbb.usernameoremailpasswordreset.listener:
        class: marttiphpbb\usernameoremailpasswordreset\event\listener
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    marttiphpbb.usernameoremailpasswordreset.console.info:
        class: marttiphpbb\usernameoremailpasswordreset\console\info
        arguments:   
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: console.command }            